name: mobile.dev
on: 
  pull_request_target:
    branches: [ master, main ]
  push:
    branches: [ master, main ]
permissions:
  actions: read
  checks: read
  contents: read
  pull-requests: read

jobs:
  upload-to-mobile-dev:
    runs-on: macos-latest
    name: Upload artifact to mobile.dev
    steps:
      - uses: actions/checkout@v3
      - name: Build x86 app
        run: |
          xcrun xcodebuild \
          -scheme RInAppMessaging-Example \
          -workspace RInAppMessaging.xcworkspace \
          -configuration Release \
          -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.5' \
          -derivedDataPath \
          build
          zip -r -X app.zip build/Build/Products/Release-iphonesimulator/RInAppMessaging_Example.app
      - uses: mobile-dev-inc/action-upload@v1.0.0
        with:
          api-key: ${{ secrets.MOBILE_DEV_API_KEY }}
          name: ${{ github.sha }}
          app-file: app.zip